export const stores_list = [
  {
    id: 1,
    country: 'KSA',
    city: 'RIYADH',
    loc_key: '35354',
    location: 'NAKHEEL MALL',
    grade: 'A+',
    area_manager: 'Mr. Ahmed Ismail',
    area_manager_no: '+966 550770546',
    store_no: 'n/a',
    store_manager: 'Faisal',
    store_manager_no: '+966599776114',
    google_map_link: 'https://goo.gl/maps/t5hu2hHWzqR1r8Kv5',
  },
  {
    id: 2,
    country: 'KSA',
    city: 'JEDDAH',
    loc_key: '72456',
    location: 'RED SEE MALL',
    grade: 'A',
    area_manager: 'Mr. Ahmed Ismail',
    area_manager_no: '+966 550770546',
    store_no: 'n/a',
    store_manager: 'Mohammed Mari Mohammed Al Samiri',
    store_manager_no: '+966545985940',
    google_map_link: 'https://goo.gl/maps/G1A4Cu19z8Kg1Puo6',
  },
  {
    id: 3,
    country: 'KSA',
    city: 'DAMMAM',
    loc_key: '12367',
    location: 'MALL OF DAHRAN',
    grade: 'B+',
    area_manager: 'Mr. Ahmed Ismail',
    area_manager_no: '+966 550770546',
    store_no: 'n/a',
    store_manager: 'Nader Mubarak Al Bishi',
    store_manager_no: '+966560001748',
    google_map_link: 'https://goo.gl/maps/UbpfpXWMgxEL5KjKA',
  },
  {
    id: 4,
    country: 'KSA',
    city: 'JEDDAH',
    loc_key: '55049',
    location: 'MAKKAH MALL',
    grade: 'B+',
    area_manager: 'Mr. Ahmed Ismail',
    area_manager_no: '+966 550770546',
    store_no: 'n/a',
    store_manager: 'Abdulrahman',
    store_manager_no: '+966530192484',
    google_map_link: 'https://goo.gl/maps/Ni5kUV6Kq1doBLnf6',
  },
  {
    id: 5,
    country: 'KSA',
    city: 'JEDDAH',
    loc_key: 'n/a',
    location: 'JEDDAH PARK',
    grade: 'n/a',
    area_manager: 'Mr. Ahmed Ismail',
    area_manager_no: '+966 550770546',
    store_no: 'n/a',
    store_manager: 'Foad AbdulMutaal',
    store_manager_no: '+966548988894',
    google_map_link: 'https://goo.gl/maps/6DTFXM5xiVpvKNoM7',
  },
  {
    id: 6,
    country: 'KSA',
    city: 'RIYADH',
    loc_key: '55045',
    location: 'HAYAT MALL',
    grade: 'B+',
    area_manager: 'Mr. Ahmed Ismail',
    area_manager_no: '+966 550770546',
    store_no: 'n/a',
    store_manager: 'Bandar Ahmed',
    store_manager_no: '+966568000430',
    google_map_link: 'https://goo.gl/maps/7zjBS6s4vkPrjPBH7',
  },
  {
    id: 7,
    country: 'KSA',
    city: 'RIYADH',
    loc_key: '15086',
    location: 'GALLERIA MALL',
    grade: 'B+',
    area_manager: 'Mr. Ahmed Ismail',
    area_manager_no: '+966 550770546',
    store_no: 'n/a',
    store_manager: 'Mohammed Abdulaziz Alanazi',
    store_manager_no: '+966581245245',
    google_map_link: 'https://goo.gl/maps/oTPGMKmY5t47VS77A',
  },
  {
    id: 8,
    country: 'KSA',
    city: 'RIYADH',
    loc_key: '24223',
    location: 'GRANADA MALL',
    grade: 'B',
    area_manager: 'Mr. Ahmed Ismail',
    area_manager_no: '+966 550770546',
    store_no: 'n/a',
    store_manager: 'Rawan Moid Almalki',
    store_manager_no: '+966554470879',
    google_map_link: 'https://goo.gl/maps/vrHSfr3ESB4ac6Pv7',
  },
  {
    id: 9,
    country: 'KSA',
    city: 'DAMMAM',
    loc_key: '64952',
    location: 'NAKHEEL MALL',
    grade: 'C',
    area_manager: 'Mr. Ahmed Ismail',
    area_manager_no: '+966 550770546',
    store_no: 'n/a',
    store_manager: 'Maraym Nasser Alhudarri',
    store_manager_no: '+966561913277',
    google_map_link: 'https://goo.gl/maps/pK9MfUZYdSAGGQCE8',
  },
];
